config/routes.rb
Rails.application.routes.draw do

  get 'order/create'
  #resources :cart
  #get 'cart/create/:id', to: 'cart#create', as: 'ajouter_panier'
  get 'cart/:id/create', to: 'cart#create', as: "cart_create"
  get 'cart/cat', to: 'cart#cart', as: "cart"
  #DELETE /articles/:id(.:format)      articles#destroy
  delete 'cart/cat/:id', to: 'cart#destroy', as: 'delete_cart'
  devise_for :users
  resources :items

  root to: "home#index"
  get 'home/mailer', to: 'home#mailer', as: 'panier'
  #ressouces :contacts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/associate_item_cart.rb
class AssociateItemCart < ApplicationRecord
    belongs_to :item
    belongs_to :cart
end

app/models/associate_order_item.rb
class AssociateOrderItem < ApplicationRecord
    belongs_to :item
    belongs_to :order
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :associate_item_cart 
    has_many :item, through: :associate_item_carts
end

app/models/item.rb
class Item < ApplicationRecord
    has_many :associate_item_carts
    has_many :cart, through: :associate_item_carts
    has_many :associate_order_items
    has_many :order, through: :associate_order_items

    validates :title, presence: true, uniqueness: true
    validates :description, presence: true
    validates :price, presence: true
    validates :image_url, presence: true, uniqueness: true
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
    has_many :associate_order_items
    has_many :item, through: :associate_order_items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :cart #referer au model cart
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?
    protected
    
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username, :email, :password, :remember_me])
        devise_parameter_sanitizer.permit(:sign_in, keys: [:email, :password, :remember_me])
        devise_parameter_sanitizer.permit(:sign_update, keys: [:first_name, :last_name, :username, :email, :password, :current_password, :remember_me])
    end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  
  def cart
  	if user_signed_in?
  		@cart = Cart.find_by(user_id: current_user.id)
      associations = AssociateItemCart.where(cart_id: @cart.id)
      if associations != nil
        @items = []
        associations.each do |a|
          @items.push(Item.find(a.item_id))
        end
        if @cart != nil
          associations = AssociateItemCart.where(cart_id: @cart.id)
          @items = []
          associations.each do |a|
            @items.push(Item.find(a.item_id))
          end
          #redirect_to cart_path
        else
          @cart = Cart.new
          current_user.cart = @cart
          @cart.save
          @items = []
          #redirect_to cart_path
        end
      end 
      
  	else
  		redirect_to(user_session_path)
  	end
  end

  def create
    if user_signed_in?
      # tadiavina @ alalan'ilay id-any ilay item
         item = Item.find(params[:id])
      # jerena ny panier anle user connecté
         @cart = Cart.find_by(user_id: current_user.id)
      # jerena ra misy anle item selectionné anaty association
         associations = AssociateItemCart.find_by(item_id: item.id)

         # jerena ra efa manana cart ilay user
         if @cart!=nil
            # jerena ra efa associé ilay item
            if associations == nil
                assoc = AssociateItemCart.new
                assoc.item = item
                assoc.cart = @cart
                assoc.save

                flash[:success] = "Ajouté avec succés"
                # miverina eo @le item iany
                #redirect_to item_show_path(params[:id])
                puts "OKKKKKKKKKKKKK"
                redirect_to root_path
            else
                flash[:error] = "Photo déjà au panier"
                #redirect_to item_show_path(params[:id])
                puts "NOOOOONNNNNNNN"
                redirect_to root_path
            end
         else
            cart = Cart.new
            cart.user = current_user
            assoc = AssociateItemCart.new
            assoc.item = item
            assoc.cart = cart
            assoc.save

            flash[:success] = "Ajouté avec succés"
            # miverina eo @le item iany
            #redirect_to item_show_path(params[:id])
            puts "OKKKKKKKKKKKKK"
            redirect_to root_path
         end

    else
      flash[:error] = "Vous devez vous inscrire !"
  		redirect_to user_session_path
    end
  end

  def striper
    #stripe
      
    @amount = 500

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )
  
    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'eur'
    )
  
  end

  def destroy
    if user_signed_in?

      
       # envoie mail
       ContactMailer.contact(current_user, Item.first).deliver_now
        
       cart = Cart.find_by(user_id: current_user.id)
       a=AssociateItemCart.where(cart_id: cart.id)
       if a != nil
         a.each do |ass|
           ass.delete
         end
       end

        redirect_to root_path#payer_path
    else
        redirect_to root_path

    end

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  

  def index
    @chats = Item.all
    if user_signed_in?
    	@cart = Cart.find_by(user_id: current_user.id)
    	if @cart != nil
	  		associations = AssociateItemCart.where(cart_id: @cart.id)
	  		@items = []
	  		associations.each do |a|
	  			@items.push(Item.find(a.item_id))
	  		end
    	else
    		@cart = Cart.new
    		current_user.cart = @cart
    		@cart.save
    		@items = []
    	end
    end
  end

  def show
  	@cat = Item.find(params[:id])
  	if user_signed_in?
    	@cart = Cart.find_by(user_id: current_user.id)
  		associations = AssociateItemCart.where(cart_id: @cart.id)
  		@items = []
  		associations.each do |a|
  			@items.push(Item.find(a.item_id))
  		end
    end
	end


  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  def index
    @chats = Item.all
  end
  
  def new
    @item = Item.new
  end

  def create
    @price = params['price'].to_d
    #puts @price
    @item = Item.new(title: params['title'], description: params['description'], price: @price, image_url: params['image_url'])
    if @item.save
      redirect_to item_path(@item.id)
    else
      render "new"
    end
  end
 
  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update!(item_params)
    redirect_to item_path
  end

  private
  def item_params
    params.require(:item).permit(:title, :description, :price, :image_url)
  end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  def create
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/views/cart/cart.html.erb
<!-- Cart -->
<%  @nb = 0 
        @somme = 0
    %>
    
<section class="cart bgwhite p-t-70 p-b-100">
	<div class="container">
		<!-- Cart item -->
		<div class="container-table-cart pos-relative">
			<div class="wrap-table-shopping-cart bgwhite">
				<table class="table-shopping-cart">
					<tr class="table-head">
						<th class="column-1"></th>
						<th class="column-2">Titre de l'image</th>
						<th class="column-3">Prix</th>
						<th class="column-4 p-l-70">Description</th>
						<!-- th class="column-5">Action</th -->
					</tr>

					
                    <% @items.each do |item|  
                        @nb +=1
                        @somme += item.price %>
					<tr class="table-row">
						<td class="column-1">
							<div style="background-image:url(<%= asset_url(item.image_url) %>); height:100px" class="cart-img-product b-rad-4 o-f-hidden block-prod-for-back">
								
							</div>
						</td>
						<td class="column-2"><%= item.title %></td>
						<td class="column-3"><%= item.price %>€</td>
						<td class="column-4"><%= item.description %></td>
						<td class="column-5">
							<div class="size10 trans-0-4 m-t-10 m-b-10">
							
							<!-- button class="flex-c-m sizefull bg1 bo-rad-23 hov1 s-text1 trans-0-4">
								<i class="fa fa-trash" aria-hidden="true"></i> &nbsp;Supprimer
							</button -->
							</div>
						</td>
                    </tr>
                    <% end %>
                    
				</table>
			</div>
		</div>


		<!-- Total -->
		<%= form_tag items_path do %>
		<div class="bo9 w-size18 p-l-40 p-r-40 p-t-30 p-b-38 m-t-30 m-r-0 m-l-auto p-lr-15-sm">
			<h5 class="m-text20 p-b-24">
				Total du panier
			</h5>
			<!--  -->
			<div class="flex-w flex-sb-m p-t-26 p-b-30">
				<span class="m-text22 w-size19 w-full-sm">
					Total :
				</span>

				<span class="m-text21 w-size20 w-full-sm amount">
					<%= @somme %>€
				</span>
				<%= if @nb > 0 
					render partial: 'layouts/commander'
				end %>
			</div>

			<div class="flex-w flex-sb-m p-t-26 p-b-30">
				<% if flash[:error].present? %>
			      <div id="error_explanation">
			        <p><%= flash[:error] %></p>
			      </div>
			    <% end %>
			</div>

			
		</div>
		<% end %>
	</div>
</section>

app/views/cart/cartBACK.html.erb
<div>
    <h2>IMAGES AU PANIER</h2>
    <%  @nb = 0 
        @somme = 0
    %>
    <% @items.each do |item|  
        @nb +=1
        @somme += item.price %>
        
        <div id="product" style="background-color: grey;">
            <h2>
                <%= item.title %>
            </h2>
            <div>
                <%= image_tag(item.image_url, width: '50px', height: '50px') %>
                    <%= item.description %>
            </div>
            <div>
                <%= item.image_url %>
            </div>
            <div>
                <%= item.price %>
                    <%= link_to "show", item_path(item.id) %>
                    <%= link_to "Supprimer du panier", cart_create_path(item.id) %>
            </div>
        </div>
        <% end %>
        <div>
            <span>Tu as : <%= @nb %> Items au paniers</span>
            <span>Tu dois payer <%= @somme %> €</span>
            <span><%= link_to 'Delete', delete_cart_path(current_user.id), 
                        method: :delete, 
                        data: { confirm: 'Are you sure?' } 
                    %> 
            </span>
        </div>
</div>

app/views/cart/create.html.erb
<%= form_tag items_path do %>
    <article>
      <% if flash[:error].present? %>
        <div id="error_explanation">
          <p><%= flash[:error] %></p>
        </div>
      <% end %>
      <label class="amount">
        <span>Amount: $5.00</span>
      </label>
    </article>
  
    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-description="A month's subscription"
            data-amount="500"
            data-locale="auto"></script>
  <% end %>

app/views/cart/stripe.html.erb
<!--%= form_tag delete_cart_path do %>
        <article>
            <% if flash[:error].present? %>
                <div id="error_explanation">
                    <p>
                        <%= flash[:error] %>
                    </p>
                </div>
                <% end %>
                    <label class="amount">
                        <span>Amount: $5.00</span>
                    </label>
        </article>

        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button" 
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-description="A month's subscription" 
            data-amount="500" 
            data-locale="auto">
        </script>
    <% end % -->

app/views/home/index.html.erb
    <!-- Slide1 -->
    <section class="slide1">
        <div class="wrap-slick1">
            <div class="slick1">
                <div class="item-slick1 item1-slick1" style="background-image: url(/images/slider/slide1.jpg);">
                    <div class="wrap-content-slide1 sizefull flex-col-c-m p-l-15 p-r-15 p-t-150 p-b-170">
                        <h2 class="caption1-slide1 xl-text2 t-center bo14 p-b-6 animated visible-false m-b-22" data-appear="fadeInUp">
                            Leather Bags
                        </h2>

                        <span class="caption2-slide1 m-text1 t-center animated visible-false m-b-33" data-appear="fadeInDown">
                            New Collection 2018
                        </span>

                        <div class="wrap-btn-slide1 w-size1 animated visible-false" data-appear="zoomIn">
                            <!-- Button -->
                            <a href="product.html" class="flex-c-m size2 bo-rad-23 s-text2 bgwhite hov1 trans-0-4">
                                Shop Now
                            </a>
                        </div>
                    </div>
                </div>

                <div class="item-slick1 item2-slick1" style="background-image: url(/images/slider/slide2.jpg);">
                    <div class="wrap-content-slide1 sizefull flex-col-c-m p-l-15 p-r-15 p-t-150 p-b-170">
                        <h2 class="caption1-slide1 xl-text2 t-center bo14 p-b-6 animated visible-false m-b-22" data-appear="rollIn">
                            Leather Bags
                        </h2>

                        <span class="caption2-slide1 m-text1 t-center animated visible-false m-b-33" data-appear="lightSpeedIn">
                            New Collection 2018
                        </span>

                        <div class="wrap-btn-slide1 w-size1 animated visible-false" data-appear="slideInUp">
                            <!-- Button -->
                            <a href="product.html" class="flex-c-m size2 bo-rad-23 s-text2 bgwhite hov1 trans-0-4">
                                Shop Now
                            </a>
                        </div>
                    </div>
                </div>

                <div class="item-slick1 item3-slick1" style="background-image: url(/images/slider/slide3.jpg);">
                    <div class="wrap-content-slide1 sizefull flex-col-c-m p-l-15 p-r-15 p-t-150 p-b-170">
                        <h2 class="caption1-slide1 xl-text2 t-center bo14 p-b-6 animated visible-false m-b-22" data-appear="rotateInDownLeft">
                            Leather Bags
                        </h2>

                        <span class="caption2-slide1 m-text1 t-center animated visible-false m-b-33" data-appear="rotateInUpRight">
                            New Collection 2018
                        </span>

                        <div class="wrap-btn-slide1 w-size1 animated visible-false" data-appear="rotateIn">
                            <!-- Button -->
                            <a href="product.html" class="flex-c-m size2 bo-rad-23 s-text2 bgwhite hov1 trans-0-4">
                                Shop Now
                            </a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </section>


    <!-- Our product -->
    <section class="bgwhite p-t-45 p-b-58">
        <div class="container">

            <!-- Tab01 -->
            <div class="tab01">
                <!-- Nav tabs -->
                <ul class="nav nav-tabs" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active" data-toggle="tab" href="#best-seller" role="tab">Best Seller</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="tab" href="#featured" role="tab">Featured</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="tab" href="#sale" role="tab">Sale</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="tab" href="#top-rate" role="tab">Top Rate</a>
                    </li>
                </ul>

                <!-- Tab panes -->
                <div class="tab-content p-t-35">
                    <!-- - -->
                    <div class="tab-pane fade show active" id="best-seller" role="tabpanel">
                        <div class="row">
                            <% @chats.each do |chat| %>
                            <div class="col-sm-6 col-md-4 col-lg-3 p-b-50">
                                <!-- Block2 -->
                                <div class="block2">
                                    <div style="background-image:url(<%= asset_url(chat.image_url) %>)" class="block2-img wrap-pic-w of-hidden pos-relative block2-labelnew block-prod-for-back">
                                        

                                        <div class="block2-overlay trans-0-4">
                                            <a href="#" class="block2-btn-addwishlist hov-pointer trans-0-4">
                                                <i class="icon-wishlist icon_heart_alt" aria-hidden="true"></i>
                                                <i class="icon-wishlist icon_heart dis-none" aria-hidden="true"></i>
                                            </a>

                                            <div class="block2-btn-addcart w-size1 trans-0-4">
                                                <!-- Button -->
                                           
                                                <%= link_to "Ajouter", cart_create_path(chat.id), 
                                                    class: "flex-c-m size1 bg4 bo-rad-23 hov1 s-text1 trans-0-4" %>
                                            
                                            <!-- button class="flex-c-m size1 bg4 bo-rad-23 hov1 s-text1 trans-0-4">
                                                <i class="fa fa-shopping-bag" aria-hidden="true"></i> &nbsp; Ajouter
                                            </button -->
                                                
                                            </div>
                                        </div>
                                    </div>

                                    <div class="block2-txt p-t-20">
                                        <%= link_to chat.title , item_path(chat.id), class: "block2-name dis-block s-text3 p-b-5" %>

                                        <span class="block2-price m-text6 p-r-5">
                                            <%= chat.price %> €
                                        </span>
                                    </div>
                                </div>
                            </div>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>



    <!-- Instagram -->
    <section class="instagram p-t-20">
        <div class="flex-w">
            <!-- Block4 -->
            <div class="block4 wrap-pic-w">
                <img src="images/gallery-03.jpg" alt="IMG-INSTAGRAM">

                <a href="#" class="block4-overlay sizefull ab-t-l trans-0-4">
                    <span class="block4-overlay-heart s-text9 flex-m trans-0-4 p-l-40 p-t-25">
                        <i class="icon_heart_alt fs-20 p-r-12" aria-hidden="true"></i>
                        <span class="p-t-2">39</span>
                    </span>

                    <div class="block4-overlay-txt trans-0-4 p-l-40 p-r-25 p-b-30">
                        <p class="s-text10 m-b-15 h-size1 of-hidden">
                            Nullam scelerisque, lacus sed consequat laoreet, dui enim iaculis leo, eu viverra ex nulla in tellus. Nullam nec ornare tellus, ac fringilla lacus. Ut sit amet enim orci. Nam eget metus elit.
                        </p>

                        <span class="s-text9">
                            Photo by @nancyward
                        </span>
                    </div>
                </a>
            </div>

            <!-- Block4 -->
            <div class="block4 wrap-pic-w">
                <img src="images/gallery-07.jpg" alt="IMG-INSTAGRAM">

                <a href="#" class="block4-overlay sizefull ab-t-l trans-0-4">
                    <span class="block4-overlay-heart s-text9 flex-m trans-0-4 p-l-40 p-t-25">
                        <i class="icon_heart_alt fs-20 p-r-12" aria-hidden="true"></i>
                        <span class="p-t-2">39</span>
                    </span>

                    <div class="block4-overlay-txt trans-0-4 p-l-40 p-r-25 p-b-30">
                        <p class="s-text10 m-b-15 h-size1 of-hidden">
                            Nullam scelerisque, lacus sed consequat laoreet, dui enim iaculis leo, eu viverra ex nulla in tellus. Nullam nec ornare tellus, ac fringilla lacus. Ut sit amet enim orci. Nam eget metus elit.
                        </p>

                        <span class="s-text9">
                            Photo by @nancyward
                        </span>
                    </div>
                </a>
            </div>

            <!-- Block4 -->
            <div class="block4 wrap-pic-w">
                <img src="images/gallery-09.jpg" alt="IMG-INSTAGRAM">

                <a href="#" class="block4-overlay sizefull ab-t-l trans-0-4">
                    <span class="block4-overlay-heart s-text9 flex-m trans-0-4 p-l-40 p-t-25">
                        <i class="icon_heart_alt fs-20 p-r-12" aria-hidden="true"></i>
                        <span class="p-t-2">39</span>
                    </span>

                    <div class="block4-overlay-txt trans-0-4 p-l-40 p-r-25 p-b-30">
                        <p class="s-text10 m-b-15 h-size1 of-hidden">
                            Nullam scelerisque, lacus sed consequat laoreet, dui enim iaculis leo, eu viverra ex nulla in tellus. Nullam nec ornare tellus, ac fringilla lacus. Ut sit amet enim orci. Nam eget metus elit.
                        </p>

                        <span class="s-text9">
                            Photo by @nancyward
                        </span>
                    </div>
                </a>
            </div>

            <!-- Block4 -->
            <div class="block4 wrap-pic-w">
                <img src="images/gallery-13.jpg" alt="IMG-INSTAGRAM">

                <a href="#" class="block4-overlay sizefull ab-t-l trans-0-4">
                    <span class="block4-overlay-heart s-text9 flex-m trans-0-4 p-l-40 p-t-25">
                        <i class="icon_heart_alt fs-20 p-r-12" aria-hidden="true"></i>
                        <span class="p-t-2">39</span>
                    </span>

                    <div class="block4-overlay-txt trans-0-4 p-l-40 p-r-25 p-b-30">
                        <p class="s-text10 m-b-15 h-size1 of-hidden">
                            Nullam scelerisque, lacus sed consequat laoreet, dui enim iaculis leo, eu viverra ex nulla in tellus. Nullam nec ornare tellus, ac fringilla lacus. Ut sit amet enim orci. Nam eget metus elit.
                        </p>

                        <span class="s-text9">
                            Photo by @nancyward
                        </span>
                    </div>
                </a>
            </div>

            <!-- Block4 -->
            <div class="block4 wrap-pic-w">
                <img src="images/gallery-15.jpg" alt="IMG-INSTAGRAM">

                <a href="#" class="block4-overlay sizefull ab-t-l trans-0-4">
                    <span class="block4-overlay-heart s-text9 flex-m trans-0-4 p-l-40 p-t-25">
                        <i class="icon_heart_alt fs-20 p-r-12" aria-hidden="true"></i>
                        <span class="p-t-2">39</span>
                    </span>

                    <div class="block4-overlay-txt trans-0-4 p-l-40 p-r-25 p-b-30">
                        <p class="s-text10 m-b-15 h-size1 of-hidden">
                            Nullam scelerisque, lacus sed consequat laoreet, dui enim iaculis leo, eu viverra ex nulla in tellus. Nullam nec ornare tellus, ac fringilla lacus. Ut sit amet enim orci. Nam eget metus elit.
                        </p>

                        <span class="s-text9">
                            Photo by @nancyward
                        </span>
                    </div>
                </a>
            </div>
        </div>
    </section>

    <!-- Shipping -->
    <section class="shipping bgwhite p-t-62 p-b-46">
        <div class="flex-w p-l-15 p-r-15">
            <div class="flex-col-c w-size5 p-l-15 p-r-15 p-t-16 p-b-15 respon1">
                <h4 class="m-text12 t-center">
                    Free Delivery Worldwide
                </h4>

                <a href="#" class="s-text11 t-center">
                    Click here for more info
                </a>
            </div>

            <div class="flex-col-c w-size5 p-l-15 p-r-15 p-t-16 p-b-15 bo2 respon2">
                <h4 class="m-text12 t-center">
                    30 Days Return
                </h4>

                <span class="s-text11 t-center">
                    Simply return it within 30 days for an exchange.
                </span>
            </div>

            <div class="flex-col-c w-size5 p-l-15 p-r-15 p-t-16 p-b-15 respon1">
                <h4 class="m-text12 t-center">
                    Store Opening
                </h4>

                <span class="s-text11 t-center">
                    Shop open from Monday to Sunday
                </span>
            </div>
        </div>
    </section>
    

app/views/home/indexBack.html.erb
<div class="container">
    <span>*******************************</span>
    <% @chats.each do |chat| %>
        <div id="product" style="background-color: grey;">
            <h2>
                <%= chat.title %>
            </h2>
            <div>
                <%= image_tag(chat.image_url, width: '50px', height: '50px') %>
                    <%= chat.description %>
            </div>
            <div>
                <%= chat.image_url %>
            </div>
            <div>
                <%= chat.price %>
                    <%= link_to "show", item_path(chat.id) %>
                    <%= link_to "Ajouter à mon panier", cart_create_path(chat.id) %>
            </div>
        </div>
        <% end %>

</div>
<div>
    <span>*******************************</span>
</div>
<div>

    <h2>MAILER</h2>
    <%= if user_signed_in? 
            link_to 'envoyer mail (lié au validation command)', panier_path
        end 
    %>
</div>
<div>
    <span>*******************************</span>
</div>
<div>
        <%= link_to 'voir mon panier', cart_path %>
</div>
    

app/views/items/edit.html.erb
<h1>Editer l'item</h1>

<%= form_for @item do |f| %>

        <label for="title">Titre</label>
        <%= f.text_field :title %>

        <label for="description">Description</label>
        <%= f.text_area :description, class: 'description' %>

        <label for="price">Prix</label>
        <%= f.text_field :price %>

        <label for="image_url">Url image</label>
        <%= f.text_field :image_url %>

        <button type="submit">Editer l'item</button>

<% end %>

app/views/items/show.html.erb
<div class="container bgwhite p-t-35 p-b-80">
	<div class="flex-w flex-sb">
		<div class="w-size13 p-t-30 respon5">
			<div class="wrap-slick3 flex-sb flex-w">
				<%= image_tag(@item.image_url, class: "show-img-max") %>
			</div>
		</div>

		<div class="w-size14 p-t-30 respon5">
			<h4 class="product-detail-name m-text16 p-b-13">
				<%= @item.title %>
			</h4>

			<span class="m-text17">
				<%= @item.price %> €
			</span>

			<div class="wrap-dropdown-content bo6 p-t-15 p-b-14 active-dropdown-content">
				<h5 class="js-toggle-dropdown-content flex-sb-m cs-pointer m-text19 color0-hov trans-0-4">
					Description
					<i class="down-mark fs-12 color1 fa fa-minus dis-none" aria-hidden="true"></i>
					<i class="up-mark fs-12 color1 fa fa-plus" aria-hidden="true"></i>
				</h5>

				<div class="dropdown-content dis-none p-t-15 p-b-23">
					<p class="s-text8">
						<%= @item.description %>
					</p>
				</div>
			</div>

			<!--  -->
			<div class="p-t-33 p-b-60">
				<div class="flex-w p-t-10">
					<div class="w-size16 flex-m flex-w">
						<div class="btn-addcart-product-detail size9 trans-0-4 m-t-10 m-b-10 btn-addcart-for-margin">
							<!-- Button -->
							<%= link_to "Ajouter", cart_create_path(@item.id), class: "flex-c-m sizefull bg1 bo-rad-23 hov1 s-text1 trans-0-4" %>
							
							<%= if user_signed_in?
								if current_user.email == "test@sayna.com"
									link_to "Editer", edit_item_path(@item.id), class: "flex-c-m sizefull bg1 bo-rad-23 hov1 s-text1 trans-0-4"
								end
							end %> 
							<!-- button class="flex-c-m sizefull bg1 bo-rad-23 hov1 s-text1 trans-0-4">
								Add to Cart
							</button -->
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/layouts/_ajouter.html.erb
<li>
    <a href="<%= new_item_path %>">Ajout photos</a>
</li>

app/views/layouts/_commander.html.erb
<span class="flex-c-m sizefull bg1 bo-rad-23 hov1 s-text1 trans-0-4">
    
            <%= link_to 'Commander', delete_cart_path(:id), 
                    method: :delete, 
                    data: { confirm: 'Are you sure?' } 
                	%>
</span>